exclude:
-   README.md
-   rollup.config.js
-   src/

disqus:
    shortname: zhenlige # 占位符，实际使用giscus评论系统

collections:
    posts:
        output: true
        permalink: /blog/:year-:month-:day/:title
    drafts:
        output: true
        permalink: /blog/draft/:title

defaults:
-   scope:
        path: ""
    values:
        layout: default
-   scope:
        path: ""
        type: pages
    values:
        layout: page
-   scope:
        path: ""
        type: posts
    values:
        layout: post
-   scope:
        path: ""
        type: drafts
    values:
        layout: post
        comments: false

plugins:
-   jekyll-archives

jekyll-archives:
    enabled:
        - categories
        - tags
    layouts:
        category: archives
        tag: archives
    permalinks:
        category: /blog/category/:name/
        tag: /blog/tag/:name/

theme: minima
minima:
    skin: auto

timezone: Asia/Shanghai
lang: zh-CN

author: 真理哥
title: 真理哥的博客
description: 个人博客/技术/geek/数学/计算机